[package]
name = "wordle-again"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
fnv = "1.0.7"
nohash-hasher = "0.2.0"
rand = "0.8.5"
